authors:
  leonardo:
    name: Leonardo Ulises Spairani
    description: Data Scientist and Python Developer
    avatar: https://avatars.githubusercontent.com/u/7612578?s=400&u=72f1b5ee3dfe65095b8cd39aee611e8a4260a99b&v=4