# minima theme instructions https://github.com/jekyll/minima
title: Leonardo Spairani

description: >- 
  Personal site and blog about Data Science, Technology and Python development.
baseurl: ""
url: ""
twitter_username: LU_Spairani
github_username:  lus24

theme: minima
plugins:
  - jekyll-feed

show_excerpts: true
